version: 3
endpoint: https://test-mullayan.hasura.app
admin_secret: fVgXTASFaLUkz5TEqHjp5zNOdW2gpZjS2CZDIEosBYEVTIBnZMqcIpLEylkBB5kh
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
